# Generated by Django 5.0.6 on 2026-06-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountgroup",
            name="code",
            field=models.CharField(max_length=12),
        ),
    ]
