"""Category-driven COA template data (generated from FinCare_Chart_of_Accounts.xlsx).

Do not hand-edit row data; regenerate from the workbook source if it changes.
Each row: main/sub/charge segments, names, account_type, vat (default code),
normal (balance override or None), control (bool), subledger, bank (bool).
"""

# category key -> COA band digit (first digit of the entity code)
BANDS = {
    "transport": "1",
    "cafeteria": "2",
    "baqala": "3",
    "salon": "4",
    "tour": "5",
    "restaurant": "6",
    "car_rental": "7",
    "typing": "8",
    "pharmacy": "9",
    "workshop": "0",
}

CATEGORY_LABELS = {
    "transport": "Transport",
    "cafeteria": "Cafeteria",
    "baqala": "Baqala / Grocery",
    "salon": "Gents Salon",
    "tour": "Tours & Travel",
    "restaurant": "Restaurant",
    "car_rental": "Car Rental",
    "typing": "Typing Centre",
    "pharmacy": "Pharmacy",
    "workshop": "Auto Workshop",
}

NEEDS_INVENTORY = {
    "transport": False,
    "cafeteria": True,
    "baqala": True,
    "salon": True,
    "tour": False,
    "restaurant": True,
    "car_rental": False,
    "typing": False,
    "pharmacy": True,
    "workshop": True,
}

BACKBONE = [
    {
        "main": "100",
        "main_name": "ASSETS",
        "sub": "110",
        "sub_name": "Cash & Bank",
        "charge": "001",
        "name": "Petty Cash",
        "account_type": "cash",
        "vat": "NA",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "100",
        "main_name": "ASSETS",
        "sub": "110",
        "sub_name": "Cash & Bank",
        "charge": "002",
        "name": "Cash in Hand",
        "account_type": "cash",
        "vat": "NA",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "100",
        "main_name": "ASSETS",
        "sub": "110",
        "sub_name": "Cash & Bank",
        "charge": "010",
        "name": "Bank - ENBD Current A/C",
        "account_type": "bank",
        "vat": "NA",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": True,
    },
    {
        "main": "100",
        "main_name": "ASSETS",
        "sub": "110",
        "sub_name": "Cash & Bank",
        "charge": "011",
        "name": "Bank - ADCB Current A/C",
        "account_type": "bank",
        "vat": "NA",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": True,
    },
    {
        "main": "100",
        "main_name": "ASSETS",
        "sub": "110",
        "sub_name": "Cash & Bank",
        "charge": "020",
        "name": "POS / Card Settlement Clearing",
        "account_type": "general",
        "vat": "NA",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "100",
        "main_name": "ASSETS",
        "sub": "120",
        "sub_name": "Trade & Other Receivables",
        "charge": "001",
        "name": "Trade Receivables - Control",
        "account_type": "receivable",
        "vat": "NA",
        "normal": None,
        "control": True,
        "subledger": "customer",
        "bank": False,
    },
    {
        "main": "100",
        "main_name": "ASSETS",
        "sub": "120",
        "sub_name": "Trade & Other Receivables",
        "charge": "002",
        "name": "Advances to Suppliers",
        "account_type": "general",
        "vat": "NA",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "100",
        "main_name": "ASSETS",
        "sub": "120",
        "sub_name": "Trade & Other Receivables",
        "charge": "003",
        "name": "Staff Advances",
        "account_type": "general",
        "vat": "NA",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "100",
        "main_name": "ASSETS",
        "sub": "120",
        "sub_name": "Trade & Other Receivables",
        "charge": "004",
        "name": "Prepaid Expenses",
        "account_type": "general",
        "vat": "NA",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "100",
        "main_name": "ASSETS",
        "sub": "120",
        "sub_name": "Trade & Other Receivables",
        "charge": "005",
        "name": "VAT Refundable / Receivable",
        "account_type": "general",
        "vat": "NA",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "100",
        "main_name": "ASSETS",
        "sub": "120",
        "sub_name": "Trade & Other Receivables",
        "charge": "006",
        "name": "Deposits (RTA, DEWA, Rent)",
        "account_type": "general",
        "vat": "NA",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "100",
        "main_name": "ASSETS",
        "sub": "150",
        "sub_name": "Property, Plant & Equipment",
        "charge": "003",
        "name": "Furniture & Fixtures - Cost",
        "account_type": "fixed_asset",
        "vat": "SR",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "100",
        "main_name": "ASSETS",
        "sub": "150",
        "sub_name": "Property, Plant & Equipment",
        "charge": "004",
        "name": "Furniture & Fixtures - Acc. Depreciation",
        "account_type": "fixed_asset",
        "vat": "NA",
        "normal": "C",
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "100",
        "main_name": "ASSETS",
        "sub": "150",
        "sub_name": "Property, Plant & Equipment",
        "charge": "005",
        "name": "Office Equipment - Cost",
        "account_type": "fixed_asset",
        "vat": "SR",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "100",
        "main_name": "ASSETS",
        "sub": "150",
        "sub_name": "Property, Plant & Equipment",
        "charge": "006",
        "name": "Office Equipment - Acc. Depreciation",
        "account_type": "fixed_asset",
        "vat": "NA",
        "normal": "C",
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "200",
        "main_name": "LIABILITIES",
        "sub": "210",
        "sub_name": "Trade & Other Payables",
        "charge": "001",
        "name": "Trade Payables - Control",
        "account_type": "payable",
        "vat": "NA",
        "normal": None,
        "control": True,
        "subledger": "supplier",
        "bank": False,
    },
    {
        "main": "200",
        "main_name": "LIABILITIES",
        "sub": "210",
        "sub_name": "Trade & Other Payables",
        "charge": "002",
        "name": "Accrued Expenses",
        "account_type": "general",
        "vat": "NA",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "200",
        "main_name": "LIABILITIES",
        "sub": "210",
        "sub_name": "Trade & Other Payables",
        "charge": "003",
        "name": "Advances from Customers",
        "account_type": "general",
        "vat": "NA",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "200",
        "main_name": "LIABILITIES",
        "sub": "210",
        "sub_name": "Trade & Other Payables",
        "charge": "004",
        "name": "Other Payables",
        "account_type": "general",
        "vat": "NA",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "200",
        "main_name": "LIABILITIES",
        "sub": "230",
        "sub_name": "Tax Liabilities",
        "charge": "001",
        "name": "Output VAT",
        "account_type": "vat_output",
        "vat": "NA",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "200",
        "main_name": "LIABILITIES",
        "sub": "230",
        "sub_name": "Tax Liabilities",
        "charge": "002",
        "name": "Input VAT",
        "account_type": "vat_input",
        "vat": "NA",
        "normal": "D",
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "200",
        "main_name": "LIABILITIES",
        "sub": "230",
        "sub_name": "Tax Liabilities",
        "charge": "003",
        "name": "VAT Payable - Net",
        "account_type": "general",
        "vat": "NA",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "200",
        "main_name": "LIABILITIES",
        "sub": "230",
        "sub_name": "Tax Liabilities",
        "charge": "004",
        "name": "Corporate Tax Payable",
        "account_type": "general",
        "vat": "NA",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "200",
        "main_name": "LIABILITIES",
        "sub": "240",
        "sub_name": "Employee Liabilities",
        "charge": "001",
        "name": "Salaries Payable / WPS Clearing",
        "account_type": "general",
        "vat": "NA",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "200",
        "main_name": "LIABILITIES",
        "sub": "240",
        "sub_name": "Employee Liabilities",
        "charge": "002",
        "name": "End of Service Gratuity Provision",
        "account_type": "general",
        "vat": "NA",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "200",
        "main_name": "LIABILITIES",
        "sub": "240",
        "sub_name": "Employee Liabilities",
        "charge": "003",
        "name": "Leave Salary Provision",
        "account_type": "general",
        "vat": "NA",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "300",
        "main_name": "EQUITY",
        "sub": "310",
        "sub_name": "Capital",
        "charge": "001",
        "name": "Owner's / Share Capital",
        "account_type": "equity",
        "vat": "NA",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "300",
        "main_name": "EQUITY",
        "sub": "310",
        "sub_name": "Capital",
        "charge": "002",
        "name": "Partner / Shareholder Current A/C",
        "account_type": "equity",
        "vat": "NA",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "300",
        "main_name": "EQUITY",
        "sub": "320",
        "sub_name": "Reserves & Results",
        "charge": "001",
        "name": "Retained Earnings",
        "account_type": "equity",
        "vat": "NA",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "300",
        "main_name": "EQUITY",
        "sub": "320",
        "sub_name": "Reserves & Results",
        "charge": "002",
        "name": "Current Year Profit & Loss",
        "account_type": "equity",
        "vat": "NA",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "300",
        "main_name": "EQUITY",
        "sub": "320",
        "sub_name": "Reserves & Results",
        "charge": "003",
        "name": "Drawings",
        "account_type": "equity",
        "vat": "NA",
        "normal": "D",
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "400",
        "main_name": "INCOME",
        "sub": "420",
        "sub_name": "Other Income",
        "charge": "001",
        "name": "Interest Income",
        "account_type": "revenue",
        "vat": "OS",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "400",
        "main_name": "INCOME",
        "sub": "420",
        "sub_name": "Other Income",
        "charge": "002",
        "name": "Gain on Disposal of Asset",
        "account_type": "revenue",
        "vat": "OS",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "400",
        "main_name": "INCOME",
        "sub": "420",
        "sub_name": "Other Income",
        "charge": "003",
        "name": "Miscellaneous Income",
        "account_type": "revenue",
        "vat": "SR",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "600",
        "main_name": "OVERHEAD & ADMIN EXPENSES",
        "sub": "610",
        "sub_name": "Staff Cost - Admin",
        "charge": "001",
        "name": "Admin Salaries & Wages",
        "account_type": "expense",
        "vat": "OS",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "600",
        "main_name": "OVERHEAD & ADMIN EXPENSES",
        "sub": "610",
        "sub_name": "Staff Cost - Admin",
        "charge": "002",
        "name": "Gratuity Expense",
        "account_type": "expense",
        "vat": "OS",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "600",
        "main_name": "OVERHEAD & ADMIN EXPENSES",
        "sub": "610",
        "sub_name": "Staff Cost - Admin",
        "charge": "003",
        "name": "Leave Salary Expense",
        "account_type": "expense",
        "vat": "OS",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "600",
        "main_name": "OVERHEAD & ADMIN EXPENSES",
        "sub": "610",
        "sub_name": "Staff Cost - Admin",
        "charge": "004",
        "name": "Staff Visa & Medical",
        "account_type": "expense",
        "vat": "SR",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "600",
        "main_name": "OVERHEAD & ADMIN EXPENSES",
        "sub": "620",
        "sub_name": "Premises",
        "charge": "001",
        "name": "Rent",
        "account_type": "expense",
        "vat": "SR",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "600",
        "main_name": "OVERHEAD & ADMIN EXPENSES",
        "sub": "620",
        "sub_name": "Premises",
        "charge": "002",
        "name": "Electricity & Water (DEWA)",
        "account_type": "expense",
        "vat": "SR",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "600",
        "main_name": "OVERHEAD & ADMIN EXPENSES",
        "sub": "620",
        "sub_name": "Premises",
        "charge": "003",
        "name": "Telephone & Internet",
        "account_type": "expense",
        "vat": "SR",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "600",
        "main_name": "OVERHEAD & ADMIN EXPENSES",
        "sub": "640",
        "sub_name": "General & Administrative",
        "charge": "001",
        "name": "Office Supplies & Stationery",
        "account_type": "expense",
        "vat": "SR",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "600",
        "main_name": "OVERHEAD & ADMIN EXPENSES",
        "sub": "640",
        "sub_name": "General & Administrative",
        "charge": "002",
        "name": "Legal & Professional Fees",
        "account_type": "expense",
        "vat": "SR",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "600",
        "main_name": "OVERHEAD & ADMIN EXPENSES",
        "sub": "640",
        "sub_name": "General & Administrative",
        "charge": "003",
        "name": "Trade Licence & Govt Fees",
        "account_type": "expense",
        "vat": "OS",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "600",
        "main_name": "OVERHEAD & ADMIN EXPENSES",
        "sub": "640",
        "sub_name": "General & Administrative",
        "charge": "004",
        "name": "Bank Charges",
        "account_type": "expense",
        "vat": "EX",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "600",
        "main_name": "OVERHEAD & ADMIN EXPENSES",
        "sub": "640",
        "sub_name": "General & Administrative",
        "charge": "005",
        "name": "IT & Software Subscriptions",
        "account_type": "expense",
        "vat": "SR",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "600",
        "main_name": "OVERHEAD & ADMIN EXPENSES",
        "sub": "640",
        "sub_name": "General & Administrative",
        "charge": "006",
        "name": "Marketing & Advertising",
        "account_type": "expense",
        "vat": "SR",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "600",
        "main_name": "OVERHEAD & ADMIN EXPENSES",
        "sub": "640",
        "sub_name": "General & Administrative",
        "charge": "099",
        "name": "Miscellaneous Expense",
        "account_type": "expense",
        "vat": "SR",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "600",
        "main_name": "OVERHEAD & ADMIN EXPENSES",
        "sub": "650",
        "sub_name": "Depreciation",
        "charge": "001",
        "name": "Depreciation - Furniture & Fixtures",
        "account_type": "expense",
        "vat": "NA",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "600",
        "main_name": "OVERHEAD & ADMIN EXPENSES",
        "sub": "650",
        "sub_name": "Depreciation",
        "charge": "002",
        "name": "Depreciation - Office Equipment",
        "account_type": "expense",
        "vat": "NA",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "700",
        "main_name": "FINANCE COST & TAX",
        "sub": "710",
        "sub_name": "Finance Cost",
        "charge": "001",
        "name": "Loan Interest Expense",
        "account_type": "expense",
        "vat": "EX",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "700",
        "main_name": "FINANCE COST & TAX",
        "sub": "710",
        "sub_name": "Finance Cost",
        "charge": "002",
        "name": "Bank Interest Expense",
        "account_type": "expense",
        "vat": "EX",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "700",
        "main_name": "FINANCE COST & TAX",
        "sub": "720",
        "sub_name": "Tax Expense",
        "charge": "001",
        "name": "Corporate Tax Expense",
        "account_type": "expense",
        "vat": "OS",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "700",
        "main_name": "FINANCE COST & TAX",
        "sub": "730",
        "sub_name": "Other / Exceptional",
        "charge": "001",
        "name": "Loss on Disposal of Asset",
        "account_type": "expense",
        "vat": "OS",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "700",
        "main_name": "FINANCE COST & TAX",
        "sub": "730",
        "sub_name": "Other / Exceptional",
        "charge": "002",
        "name": "Bad Debts Written Off",
        "account_type": "expense",
        "vat": "OS",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
    {
        "main": "700",
        "main_name": "FINANCE COST & TAX",
        "sub": "730",
        "sub_name": "Other / Exceptional",
        "charge": "003",
        "name": "Fines & Penalties",
        "account_type": "expense",
        "vat": "OS",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
]

INVENTORY = [
    {
        "main": "100",
        "main_name": "ASSETS",
        "sub": "130",
        "sub_name": "Inventory",
        "charge": "001",
        "name": "Inventory - Goods for Resale",
        "account_type": "general",
        "vat": "NA",
        "normal": None,
        "control": False,
        "subledger": "",
        "bank": False,
    },
]

CATEGORY_SPECS = {
    "transport": [
        {
            "main": "100",
            "main_name": "ASSETS",
            "sub": "150",
            "sub_name": "Property, Plant & Equipment",
            "charge": "001",
            "name": "Motor Vehicles - Cost",
            "account_type": "fixed_asset",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "100",
            "main_name": "ASSETS",
            "sub": "150",
            "sub_name": "Property, Plant & Equipment",
            "charge": "002",
            "name": "Motor Vehicles - Acc. Depreciation",
            "account_type": "fixed_asset",
            "vat": "NA",
            "normal": "C",
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "200",
            "main_name": "LIABILITIES",
            "sub": "220",
            "sub_name": "Loans & Borrowings",
            "charge": "001",
            "name": "Vehicle Loan Payable",
            "account_type": "loan",
            "vat": "NA",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "001",
            "name": "Uber Earnings",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "002",
            "name": "Yango Earnings",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "003",
            "name": "Bolt Earnings",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "004",
            "name": "Careem Earnings",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "006",
            "name": "Personal / Street Trip Earnings",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "007",
            "name": "Corporate Contract Revenue",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "008",
            "name": "Monthly Rental / Contract Revenue",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "415",
            "sub_name": "Recoveries from Drivers",
            "charge": "001",
            "name": "Salik Recovery",
            "account_type": "revenue",
            "vat": "OS",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "415",
            "sub_name": "Recoveries from Drivers",
            "charge": "002",
            "name": "Traffic / RTA Fine Recovery",
            "account_type": "revenue",
            "vat": "OS",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "DIRECT OPERATING COST",
            "sub": "510",
            "sub_name": "Vehicle Running Cost",
            "charge": "001",
            "name": "Salik Charges",
            "account_type": "expense",
            "vat": "OS",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "DIRECT OPERATING COST",
            "sub": "510",
            "sub_name": "Vehicle Running Cost",
            "charge": "002",
            "name": "Darb Charges",
            "account_type": "expense",
            "vat": "OS",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "DIRECT OPERATING COST",
            "sub": "510",
            "sub_name": "Vehicle Running Cost",
            "charge": "003",
            "name": "Fuel",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "DIRECT OPERATING COST",
            "sub": "510",
            "sub_name": "Vehicle Running Cost",
            "charge": "004",
            "name": "Traffic & RTA Fines",
            "account_type": "expense",
            "vat": "OS",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "DIRECT OPERATING COST",
            "sub": "510",
            "sub_name": "Vehicle Running Cost",
            "charge": "006",
            "name": "Vehicle Maintenance & Repair",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "DIRECT OPERATING COST",
            "sub": "510",
            "sub_name": "Vehicle Running Cost",
            "charge": "008",
            "name": "Vehicle Wash & Cleaning",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "DIRECT OPERATING COST",
            "sub": "520",
            "sub_name": "Platform Commission",
            "charge": "001",
            "name": "Uber Commission",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "DIRECT OPERATING COST",
            "sub": "520",
            "sub_name": "Platform Commission",
            "charge": "002",
            "name": "Yango Commission",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "DIRECT OPERATING COST",
            "sub": "520",
            "sub_name": "Platform Commission",
            "charge": "004",
            "name": "Careem Commission",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "DIRECT OPERATING COST",
            "sub": "530",
            "sub_name": "Driver Cost",
            "charge": "001",
            "name": "Driver Salary",
            "account_type": "expense",
            "vat": "OS",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "DIRECT OPERATING COST",
            "sub": "530",
            "sub_name": "Driver Cost",
            "charge": "002",
            "name": "Driver Commission",
            "account_type": "expense",
            "vat": "OS",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "DIRECT OPERATING COST",
            "sub": "530",
            "sub_name": "Driver Cost",
            "charge": "003",
            "name": "Driver Payout",
            "account_type": "expense",
            "vat": "OS",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "DIRECT OPERATING COST",
            "sub": "530",
            "sub_name": "Driver Cost",
            "charge": "005",
            "name": "Driver Visa & Emirates ID",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "DIRECT OPERATING COST",
            "sub": "530",
            "sub_name": "Driver Cost",
            "charge": "006",
            "name": "Driver Daman / Health Insurance",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "600",
            "main_name": "OVERHEAD & ADMIN EXPENSES",
            "sub": "630",
            "sub_name": "Vehicle Ownership Cost",
            "charge": "001",
            "name": "Vehicle Insurance",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "600",
            "main_name": "OVERHEAD & ADMIN EXPENSES",
            "sub": "630",
            "sub_name": "Vehicle Ownership Cost",
            "charge": "002",
            "name": "Mulkiya / Registration Renewal",
            "account_type": "expense",
            "vat": "OS",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "600",
            "main_name": "OVERHEAD & ADMIN EXPENSES",
            "sub": "630",
            "sub_name": "Vehicle Ownership Cost",
            "charge": "003",
            "name": "Vehicle Depreciation",
            "account_type": "expense",
            "vat": "NA",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
    ],
    "cafeteria": [
        {
            "main": "100",
            "main_name": "ASSETS",
            "sub": "150",
            "sub_name": "Property, Plant & Equipment",
            "charge": "007",
            "name": "Kitchen Equipment - Cost",
            "account_type": "fixed_asset",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "100",
            "main_name": "ASSETS",
            "sub": "150",
            "sub_name": "Property, Plant & Equipment",
            "charge": "008",
            "name": "Kitchen Equipment - Acc. Depreciation",
            "account_type": "fixed_asset",
            "vat": "NA",
            "normal": "C",
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "001",
            "name": "Counter / Walk-in Sales",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "002",
            "name": "Beverage & Juice Sales",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "003",
            "name": "Delivery - Talabat",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "004",
            "name": "Delivery - Deliveroo",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "006",
            "name": "Subscription / Catering Revenue",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "510",
            "sub_name": "Cost of Goods Sold",
            "charge": "001",
            "name": "Food & Grocery Purchases",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "510",
            "sub_name": "Cost of Goods Sold",
            "charge": "002",
            "name": "Beverage Purchases",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "510",
            "sub_name": "Cost of Goods Sold",
            "charge": "003",
            "name": "Consumables & Packaging",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "520",
            "sub_name": "Delivery Platform Commission",
            "charge": "001",
            "name": "Talabat Commission",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "520",
            "sub_name": "Delivery Platform Commission",
            "charge": "002",
            "name": "Deliveroo Commission",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "530",
            "sub_name": "Counter & Kitchen Staff",
            "charge": "001",
            "name": "Kitchen & Counter Salaries",
            "account_type": "expense",
            "vat": "OS",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "600",
            "main_name": "OVERHEAD & ADMIN EXPENSES",
            "sub": "650",
            "sub_name": "Depreciation",
            "charge": "003",
            "name": "Depreciation - Kitchen Equipment",
            "account_type": "expense",
            "vat": "NA",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
    ],
    "baqala": [
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "001",
            "name": "Counter / POS Sales",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "002",
            "name": "Credit Sales",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "003",
            "name": "Mobile Recharge Commission",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "004",
            "name": "Bill Payment Commission",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "510",
            "sub_name": "Cost of Goods Sold",
            "charge": "001",
            "name": "Goods Purchases - Grocery",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "510",
            "sub_name": "Cost of Goods Sold",
            "charge": "002",
            "name": "Goods Purchases - Beverages",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "510",
            "sub_name": "Cost of Goods Sold",
            "charge": "003",
            "name": "Goods Purchases - Tobacco",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "510",
            "sub_name": "Cost of Goods Sold",
            "charge": "004",
            "name": "Goods Purchases - Other",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "510",
            "sub_name": "Cost of Goods Sold",
            "charge": "005",
            "name": "Inventory Shrinkage / Wastage",
            "account_type": "expense",
            "vat": "OS",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
    ],
    "salon": [
        {
            "main": "100",
            "main_name": "ASSETS",
            "sub": "150",
            "sub_name": "Property, Plant & Equipment",
            "charge": "009",
            "name": "Salon Equipment - Cost",
            "account_type": "fixed_asset",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "100",
            "main_name": "ASSETS",
            "sub": "150",
            "sub_name": "Property, Plant & Equipment",
            "charge": "010",
            "name": "Salon Equipment - Acc. Depreciation",
            "account_type": "fixed_asset",
            "vat": "NA",
            "normal": "C",
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "001",
            "name": "Haircut & Grooming",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "002",
            "name": "Shaving & Beard Service",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "003",
            "name": "Hair Treatment & Spa",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "004",
            "name": "Facial & Skincare",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "005",
            "name": "Massage Service",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "006",
            "name": "Retail Product Sales",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "510",
            "sub_name": "Cost of Service & Goods",
            "charge": "001",
            "name": "Salon Consumables",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "510",
            "sub_name": "Cost of Service & Goods",
            "charge": "002",
            "name": "Retail Product Purchases",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "530",
            "sub_name": "Salon Staff",
            "charge": "001",
            "name": "Barber / Stylist Salaries",
            "account_type": "expense",
            "vat": "OS",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "530",
            "sub_name": "Salon Staff",
            "charge": "002",
            "name": "Staff Service Commission",
            "account_type": "expense",
            "vat": "OS",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "600",
            "main_name": "OVERHEAD & ADMIN EXPENSES",
            "sub": "650",
            "sub_name": "Depreciation",
            "charge": "004",
            "name": "Depreciation - Salon Equipment",
            "account_type": "expense",
            "vat": "NA",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
    ],
    "tour": [
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "001",
            "name": "Air Ticketing Commission",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "002",
            "name": "Visa Service Revenue",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "003",
            "name": "Hotel Booking Commission",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "004",
            "name": "Holiday Package Revenue",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "005",
            "name": "Travel Insurance Commission",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "006",
            "name": "Tour & Transfer Revenue",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "DIRECT OPERATING COST",
            "sub": "510",
            "sub_name": "Cost of Travel Services",
            "charge": "001",
            "name": "Airline / IATA Ticket Cost",
            "account_type": "expense",
            "vat": "OS",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "DIRECT OPERATING COST",
            "sub": "510",
            "sub_name": "Cost of Travel Services",
            "charge": "002",
            "name": "Visa Government Fees",
            "account_type": "expense",
            "vat": "OS",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "DIRECT OPERATING COST",
            "sub": "510",
            "sub_name": "Cost of Travel Services",
            "charge": "003",
            "name": "Hotel & Package Cost",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "DIRECT OPERATING COST",
            "sub": "510",
            "sub_name": "Cost of Travel Services",
            "charge": "004",
            "name": "Tour Operator / Transfer Cost",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
    ],
    "restaurant": [
        {
            "main": "100",
            "main_name": "ASSETS",
            "sub": "150",
            "sub_name": "Property, Plant & Equipment",
            "charge": "007",
            "name": "Kitchen Equipment - Cost",
            "account_type": "fixed_asset",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "100",
            "main_name": "ASSETS",
            "sub": "150",
            "sub_name": "Property, Plant & Equipment",
            "charge": "008",
            "name": "Kitchen Equipment - Acc. Depreciation",
            "account_type": "fixed_asset",
            "vat": "NA",
            "normal": "C",
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "001",
            "name": "Dine-in Sales",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "002",
            "name": "Takeaway Sales",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "003",
            "name": "Delivery - Talabat",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "004",
            "name": "Delivery - Deliveroo",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "005",
            "name": "Delivery - Noon Food",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "006",
            "name": "Catering Revenue",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "510",
            "sub_name": "Cost of Goods Sold",
            "charge": "001",
            "name": "Food Purchases",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "510",
            "sub_name": "Cost of Goods Sold",
            "charge": "002",
            "name": "Beverage Purchases",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "510",
            "sub_name": "Cost of Goods Sold",
            "charge": "003",
            "name": "Kitchen Consumables",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "510",
            "sub_name": "Cost of Goods Sold",
            "charge": "004",
            "name": "Packaging Material",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "520",
            "sub_name": "Delivery Platform Commission",
            "charge": "001",
            "name": "Talabat Commission",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "520",
            "sub_name": "Delivery Platform Commission",
            "charge": "002",
            "name": "Deliveroo Commission",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "520",
            "sub_name": "Delivery Platform Commission",
            "charge": "003",
            "name": "Noon Food Commission",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "530",
            "sub_name": "Kitchen & Service Staff",
            "charge": "001",
            "name": "Chef & Kitchen Salaries",
            "account_type": "expense",
            "vat": "OS",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "530",
            "sub_name": "Kitchen & Service Staff",
            "charge": "002",
            "name": "Service / Waiter Salaries",
            "account_type": "expense",
            "vat": "OS",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "600",
            "main_name": "OVERHEAD & ADMIN EXPENSES",
            "sub": "650",
            "sub_name": "Depreciation",
            "charge": "003",
            "name": "Depreciation - Kitchen Equipment",
            "account_type": "expense",
            "vat": "NA",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
    ],
    "car_rental": [
        {
            "main": "100",
            "main_name": "ASSETS",
            "sub": "150",
            "sub_name": "Property, Plant & Equipment",
            "charge": "001",
            "name": "Rental Fleet - Cost",
            "account_type": "fixed_asset",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "100",
            "main_name": "ASSETS",
            "sub": "150",
            "sub_name": "Property, Plant & Equipment",
            "charge": "002",
            "name": "Rental Fleet - Acc. Depreciation",
            "account_type": "fixed_asset",
            "vat": "NA",
            "normal": "C",
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "200",
            "main_name": "LIABILITIES",
            "sub": "220",
            "sub_name": "Loans & Borrowings",
            "charge": "001",
            "name": "Vehicle Loan Payable",
            "account_type": "loan",
            "vat": "NA",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "001",
            "name": "Daily Rental Revenue",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "002",
            "name": "Weekly Rental Revenue",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "003",
            "name": "Monthly Rental Revenue",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "004",
            "name": "Lease-to-Own Revenue",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "005",
            "name": "CDW / Insurance Waiver Revenue",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "006",
            "name": "Delivery & Collection Charges",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "415",
            "sub_name": "Customer Recoveries",
            "charge": "001",
            "name": "Salik Recharge to Customer",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "415",
            "sub_name": "Customer Recoveries",
            "charge": "002",
            "name": "Traffic Fine Recovery",
            "account_type": "revenue",
            "vat": "OS",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "415",
            "sub_name": "Customer Recoveries",
            "charge": "003",
            "name": "Excess Mileage Charges",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "DIRECT OPERATING COST",
            "sub": "510",
            "sub_name": "Fleet Running Cost",
            "charge": "001",
            "name": "Salik Charges",
            "account_type": "expense",
            "vat": "OS",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "DIRECT OPERATING COST",
            "sub": "510",
            "sub_name": "Fleet Running Cost",
            "charge": "003",
            "name": "Vehicle Maintenance & Repair",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "DIRECT OPERATING COST",
            "sub": "510",
            "sub_name": "Fleet Running Cost",
            "charge": "004",
            "name": "Traffic & RTA Fines",
            "account_type": "expense",
            "vat": "OS",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "DIRECT OPERATING COST",
            "sub": "510",
            "sub_name": "Fleet Running Cost",
            "charge": "008",
            "name": "Vehicle Wash & Detailing",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "600",
            "main_name": "OVERHEAD & ADMIN EXPENSES",
            "sub": "630",
            "sub_name": "Vehicle Ownership Cost",
            "charge": "001",
            "name": "Fleet Insurance",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "600",
            "main_name": "OVERHEAD & ADMIN EXPENSES",
            "sub": "630",
            "sub_name": "Vehicle Ownership Cost",
            "charge": "002",
            "name": "Mulkiya / Registration Renewal",
            "account_type": "expense",
            "vat": "OS",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "600",
            "main_name": "OVERHEAD & ADMIN EXPENSES",
            "sub": "630",
            "sub_name": "Vehicle Ownership Cost",
            "charge": "003",
            "name": "Fleet Depreciation",
            "account_type": "expense",
            "vat": "NA",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
    ],
    "typing": [
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "001",
            "name": "Typing & Documentation Fees",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "002",
            "name": "PRO / Document Clearing Service",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "003",
            "name": "Amer / Tasheel Service Commission",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "004",
            "name": "Photocopy & Printing",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "005",
            "name": "Translation Service",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "DIRECT OPERATING COST",
            "sub": "510",
            "sub_name": "Cost of Services",
            "charge": "001",
            "name": "Government Service Charges (Disbursement)",
            "account_type": "expense",
            "vat": "OS",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "DIRECT OPERATING COST",
            "sub": "510",
            "sub_name": "Cost of Services",
            "charge": "002",
            "name": "Amer/Tasheel/Tawjeeh Fees (Disbursement)",
            "account_type": "expense",
            "vat": "OS",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "DIRECT OPERATING COST",
            "sub": "510",
            "sub_name": "Cost of Services",
            "charge": "003",
            "name": "Printing Consumables",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
    ],
    "pharmacy": [
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "001",
            "name": "Prescription Medicine Sales",
            "account_type": "revenue",
            "vat": "ZR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "002",
            "name": "OTC Medicine Sales",
            "account_type": "revenue",
            "vat": "ZR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "003",
            "name": "Cosmetics & General Sales",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "004",
            "name": "Insurance Claim Revenue",
            "account_type": "revenue",
            "vat": "ZR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "510",
            "sub_name": "Cost of Goods Sold",
            "charge": "001",
            "name": "Medicine Purchases",
            "account_type": "expense",
            "vat": "ZR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "510",
            "sub_name": "Cost of Goods Sold",
            "charge": "002",
            "name": "OTC Purchases",
            "account_type": "expense",
            "vat": "ZR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "510",
            "sub_name": "Cost of Goods Sold",
            "charge": "003",
            "name": "Cosmetics & General Purchases",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
    ],
    "workshop": [
        {
            "main": "100",
            "main_name": "ASSETS",
            "sub": "150",
            "sub_name": "Property, Plant & Equipment",
            "charge": "011",
            "name": "Workshop Equipment & Tools - Cost",
            "account_type": "fixed_asset",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "100",
            "main_name": "ASSETS",
            "sub": "150",
            "sub_name": "Property, Plant & Equipment",
            "charge": "012",
            "name": "Workshop Equipment & Tools - Acc. Depreciation",
            "account_type": "fixed_asset",
            "vat": "NA",
            "normal": "C",
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "001",
            "name": "Labour / Service Revenue",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "002",
            "name": "Spare Parts Sales",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "003",
            "name": "Body & Paint Revenue",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "004",
            "name": "Periodic Maintenance Revenue",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "400",
            "main_name": "INCOME",
            "sub": "410",
            "sub_name": "Operating Revenue",
            "charge": "005",
            "name": "Recovery / Towing Revenue",
            "account_type": "revenue",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "510",
            "sub_name": "Cost of Goods & Services",
            "charge": "001",
            "name": "Spare Parts Purchases",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "510",
            "sub_name": "Cost of Goods & Services",
            "charge": "002",
            "name": "Paint & Body Materials",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "510",
            "sub_name": "Cost of Goods & Services",
            "charge": "003",
            "name": "Workshop Consumables",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "510",
            "sub_name": "Cost of Goods & Services",
            "charge": "004",
            "name": "Sublet / Outsourced Work",
            "account_type": "expense",
            "vat": "SR",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
        {
            "main": "500",
            "main_name": "COST OF SALES",
            "sub": "530",
            "sub_name": "Technical Staff",
            "charge": "001",
            "name": "Mechanic / Technician Salaries",
            "account_type": "expense",
            "vat": "OS",
            "normal": None,
            "control": False,
            "subledger": "",
            "bank": False,
        },
    ],
}


def account_rows(category_key):
    """Merged, de-duplicated, sorted account rows for a category."""
    rows = list(BACKBONE)
    if NEEDS_INVENTORY.get(category_key):
        rows += list(INVENTORY)
    rows += list(CATEGORY_SPECS[category_key])
    seen = set()
    out = []
    for r in rows:
        key = (r["main"], r["sub"], r["charge"])
        if key in seen:
            continue
        seen.add(key)
        out.append(r)
    out.sort(key=lambda r: (r["main"], r["sub"], r["charge"]))
    return out
