# Generated by Django 5.0.6 on 2026-06-29 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("tenants", "0004_userentitymembership_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="intercompanymap",
            name="due_from_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="intercompanymap",
            name="due_to_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounts.account",
            ),
        ),
    ]
