# Generated by Django 6.0.7 on 2026-07-25 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_accountgroup_code"),
        ("settings", "0004_backfill_driver_accounting_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="driveraccountingconfig",
            name="default_write_off_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounts.account",
            ),
        ),
    ]
