# Generated by Django 6.0.7 on 2026-07-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="settlement",
            name="allows_negative_net",
            field=models.BooleanField(default=False),
        ),
    ]
