# Generated by Django 6.0.7 on 2026-07-25 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_accountgroup_code"),
        ("drivers", "0003_settlement_allows_negative_net"),
    ]

    operations = [
        migrations.AddField(
            model_name="settlement",
            name="driver_receivable_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounts.account",
            ),
        ),
    ]
