# Generated by Django 5.0.6 on 2026-06-30 07:53

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_alter_accountgroup_code"),
        ("tenants", "0005_intercompanymap_due_from_account_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporateTaxReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("fiscal_year", models.PositiveSmallIntegerField()),
                ("trn", models.CharField(blank=True, max_length=20)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "accounting_net_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("adjustments", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("taxable_income", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                (
                    "zero_band_threshold",
                    models.DecimalField(decimal_places=2, default=375000, max_digits=18),
                ),
                ("tax_rate", models.DecimalField(decimal_places=3, default=9, max_digits=6)),
                ("small_business_relief", models.BooleanField(default=False)),
                ("tax_payable", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("computed", "Computed"),
                            ("filed", "Filed"),
                            ("paid", "Paid"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("computed_at", models.DateTimeField(blank=True, null=True)),
                ("filed_at", models.DateTimeField(blank=True, null=True)),
                ("filing_reference", models.CharField(blank=True, max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corporate_tax_returns",
                        to="tenants.entity",
                    ),
                ),
                (
                    "filed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["entity", "-fiscal_year"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TaxCodeRateHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("rate", models.DecimalField(decimal_places=3, max_digits=6)),
                ("effective_from", models.DateField(db_index=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tax_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rate_history",
                        to="accounts.taxcode",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["tax_code", "-effective_from"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TaxReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("trn", models.CharField(blank=True, max_length=15)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("computed", "Computed"),
                            ("filed", "Filed"),
                            ("paid", "Paid"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "total_output_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_input_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "net_vat_payable",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("computed_at", models.DateTimeField(blank=True, null=True)),
                ("filed_at", models.DateTimeField(blank=True, null=True)),
                ("filing_reference", models.CharField(blank=True, max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for a standalone (non-grouped) filer; leave blank when vat_group is set.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vat_returns",
                        to="tenants.entity",
                    ),
                ),
                (
                    "filed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vat_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vat_returns",
                        to="tenants.vatgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_end", "-created_at"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TaxReturnBox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("box_code", models.CharField(max_length=8)),
                ("label", models.CharField(max_length=128)),
                ("emirate", models.CharField(blank=True, max_length=32)),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("vat_amount", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("adjustment", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tax_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boxes",
                        to="tax.taxreturn",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["tax_return", "sort_order", "box_code"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="corporatetaxreturn",
            constraint=models.UniqueConstraint(
                fields=("entity", "fiscal_year"), name="corporate_tax_unique_entity_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="taxcoderatehistory",
            constraint=models.UniqueConstraint(
                fields=("tax_code", "effective_from"), name="tax_rate_history_unique_from"
            ),
        ),
        migrations.AddConstraint(
            model_name="taxreturn",
            constraint=models.UniqueConstraint(
                condition=models.Q(("vat_group__isnull", False)),
                fields=("vat_group", "period_start", "period_end"),
                name="tax_return_unique_group_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="taxreturn",
            constraint=models.UniqueConstraint(
                condition=models.Q(("entity__isnull", False)),
                fields=("entity", "period_start", "period_end"),
                name="tax_return_unique_entity_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="taxreturn",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("vat_group__isnull", False), ("entity__isnull", False), _connector="OR"
                ),
                name="tax_return_scope_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="taxreturnbox",
            constraint=models.UniqueConstraint(
                fields=("tax_return", "box_code"), name="tax_return_box_unique"
            ),
        ),
    ]
