# Generated by Django 5.0.6 on 2026-06-29 20:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("post", "Post"),
                            ("reverse", "Reverse"),
                            ("cancel", "Cancel"),
                            ("login", "Login"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("object_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("object_repr", models.CharField(blank=True, max_length=255)),
                ("entity_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("message", models.CharField(blank=True, max_length=255)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"], name="audit_audit_content_4c2ead_idx"
                    ),
                    models.Index(
                        fields=["entity_id", "-timestamp"], name="audit_audit_entity__e65629_idx"
                    ),
                ],
            },
        ),
    ]
