# Generated by Django 5.0.6 on 2026-06-30 11:55

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_alter_accountgroup_code"),
        ("ar", "0001_initial"),
        ("drivers", "0002_initial"),
        ("fleet", "0001_initial"),
        ("tenants", "0005_intercompanymap_due_from_account_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("contract_no", models.CharField(max_length=24)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("weekly", "Weekly")],
                        default="monthly",
                        max_length=12,
                    ),
                ),
                ("monthly_amount", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("ended", "Ended"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="ar.customer",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="drivers.driver",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="tenants.entity",
                    ),
                ),
                (
                    "revenue_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.account",
                    ),
                ),
                (
                    "tax_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.taxcode",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["entity", "contract_no"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("trip_date", models.DateField(db_index=True)),
                (
                    "trip_type",
                    models.CharField(
                        choices=[
                            ("platform", "Platform"),
                            ("personal", "Personal"),
                            ("corporate", "Corporate"),
                            ("contract", "Contract"),
                        ],
                        max_length=16,
                    ),
                ),
                ("fare", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("commission", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("salik", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("tip", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                (
                    "distance_km",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
                ),
                ("net_revenue", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recorded", "Recorded"),
                            ("invoiced", "Invoiced"),
                            ("settled", "Settled"),
                        ],
                        db_index=True,
                        default="recorded",
                        max_length=12,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="ar.customer",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="drivers.driver",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="tenants.entity",
                    ),
                ),
            ],
            options={
                "ordering": ["-trip_date", "-created_at"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
