# Generated by Django 5.0.6 on 2026-06-30 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("fleet", "0001_initial"),
        ("ledger", "0001_initial"),
        ("platforms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="platform",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trips",
                to="platforms.platform",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="revenue_journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ledger.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trips",
                to="fleet.vehicle",
            ),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.UniqueConstraint(
                fields=("entity", "contract_no"), name="bookings_contract_unique_no"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["entity", "platform", "trip_date"], name="bookings_tr_entity__6bf9f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(fields=["entity", "status"], name="bookings_tr_entity__40d17a_idx"),
        ),
    ]
