# Generated by Django 6.0.7 on 2026-07-25 05:57

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0001_initial"),
        ("fleet", "0001_initial"),
        ("ledger", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version_no", models.PositiveSmallIntegerField(default=1)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("reducing_balance", "Reducing balance"),
                            ("flat_rate", "Flat rate"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "opening_principal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "annual_interest_rate",
                    models.DecimalField(decimal_places=3, default=0, max_digits=6),
                ),
                ("term_months", models.PositiveSmallIntegerField(default=0)),
                ("first_payment_date", models.DateField()),
                (
                    "total_principal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("total_interest", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("total_payments", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("superseded", "Superseded"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["loan", "-version_no"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="vehicleloaninstallment",
            name="fleet_loan_installment_unique",
        ),
        migrations.AddField(
            model_name="vehicleloan",
            name="amortization_method",
            field=models.CharField(
                choices=[("reducing_balance", "Reducing balance"), ("flat_rate", "Flat rate")],
                default="reducing_balance",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vehicleloan",
            name="effective_annual_rate",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="vehicleloan",
            name="first_payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicleloan",
            name="quoted_flat_rate",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="vehicleloaninstallment",
            name="closing_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="vehicleloaninstallment",
            name="opening_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="vehicleloaninstallment",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="banking.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="loanschedule",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loanschedule",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loanschedule",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="schedules",
                to="fleet.vehicleloan",
            ),
        ),
        migrations.AddField(
            model_name="loanschedule",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vehicleloaninstallment",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installments",
                to="fleet.loanschedule",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicleloaninstallment",
            constraint=models.UniqueConstraint(
                fields=("schedule", "installment_no"),
                name="fleet_loan_installment_unique_in_schedule",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanschedule",
            constraint=models.UniqueConstraint(
                fields=("loan", "version_no"), name="fleet_loan_schedule_unique_version"
            ),
        ),
    ]
