# Generated by Django 6.0.7 on 2026-07-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0002_loanschedule_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanschedule",
            name="annual_interest_rate",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name="loanschedule",
            name="method",
            field=models.CharField(
                choices=[
                    ("reducing_balance", "Reducing balance"),
                    ("flat_rate", "Flat rate"),
                    ("flat_quoted_effective", "Flat quoted / effective split"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="vehicleloan",
            name="amortization_method",
            field=models.CharField(
                choices=[
                    ("reducing_balance", "Reducing balance"),
                    ("flat_rate", "Flat rate"),
                    ("flat_quoted_effective", "Flat quoted / effective split"),
                ],
                default="reducing_balance",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="vehicleloan",
            name="annual_interest_rate",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name="vehicleloan",
            name="effective_annual_rate",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name="vehicleloan",
            name="quoted_flat_rate",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
